version: ~> 1.0

import:
  - silverstripe/silverstripe-travis-shared:config/provision/standard.yml

env:
  global:
    - DB=PGSQL

# Using a custom jobs matrix as every DB=PGSQL and there is alternating PHPUNIT_SUITE's
jobs:
  fast_finish: true
  include:
    - php: 7.3
      env:
        - REQUIRE_INSTALLER="4.10.x-dev"
        - PHPUNIT_COVERAGE_TEST=1
        - PHPUNIT_SUITE="framework"
    - php: 7.4
      env:
        - REQUIRE_INSTALLER="4.11.x-dev"
        - PHPUNIT_TEST=1
        - PHPUNIT_SUITE="postgresql"
    - php: 7.4
      env:
        - REQUIRE_INSTALLER="4.x-dev"
        - PHPUNIT_TEST=1
        - PHPUNIT_SUITE="framework"
    - php: 8.0
      env:
        - REQUIRE_INSTALLER="4.x-dev"
        - PHPUNIT_TEST=1
        - PHPUNIT_SUITE="postgresql"
    - php: 8.1
      env:
        - REQUIRE_INSTALLER="4.x-dev"
        - PHPUNIT_TEST=1
        - PHPUNIT_SUITE="framework"
