name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    name: CI
    uses: silverstripe/gha-ci/.github/workflows/ci.yml@v1
    with:
      # set phpunit to false to prevent automatic generation of mysql phpunit jobs
      phpunit: false
      extra_jobs: |
        - php: 7.4
          db: pgsql
          phpunit: true
          composer_args: --prefer-lowest
        - php: 8.0
          db: pgsql
          phpunit: true
        - php: 8.1
          db: pgsql
          phpunit: true
